---
# handlers file for shipping
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Shipping Service
  ansible.builtin.systemd:
    name: shipping
    state: restarted
