---
# tasks file for catalogue

#Setting-up Basic Roboshop Application Requirements
- name: Run Roboshop Basic App Requirements (From common for Catalogue microservice)
  ansible.builtin.import_role:
    name: common
    tasks_from: roboshop_basic_requirements.yml

#Setting-up NodeJS
- name: Installing NodeJS (From common for catalogue microservice)
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs_installation.yml

#Setting-up Catalogue Microservice
- name: Downloading Catalogue Application Code
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/catalogue.zip"
    dest: "/tmp/catalogue.zip"

- name: Unzipping Catalogue Application Code into /app
  ansible.builtin.unarchive:
    src: "/tmp/catalogue.zip"
    dest: "/app"
    remote_src: true

- name: Installing Catalogue Application Dependencies
  ansible.builtin.command: "npm install"
  args:
    chdir: /app
    creates: /app/node_modules

- name: Copying catalogue.service.j2 as /etc/systemd/system/catalogue.service
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service
    mode: "0644"
  notify: Reload Daemon

- name: Enabling and Starting Catalogue Service
  ansible.builtin.systemd:
    name: catalogue
    state: started
    enabled: true

#Loading Catalogue Schema into MongoDB Database
- name: Installing mongodb.repo (From common for catalogue microservice)
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb_repo.yml

- name: Installing MongoDB Client
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: Loading Catalogue Schema into MongoDB Database
  ansible.builtin.shell: "mongo --host mongodb.optimusprime.sbs </app/schema/catalogue.js"
