---
# tasks file for catalogue

#Setting-up Basic Roboshop Application Requirements
- name: Creating Roboshop Default App Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Creating Roboshop Default Log Directory
  ansible.builtin.file:
    path: /app/log
    state: directory

- name: Creating Catalogue Log file
  ansible.builtin.file:
    path: /app/log/catalogue_date_time.log
    state: touch

- name: Creating Roboshop Default Service User (roboshop) with Password
  ansible.builtin.user:
    name: roboshop
    state: present
    create_home: true
    shell: /bin/bash
    password: "{{roboshop_password_hash}}"
    update_password: on_create

- name: Creating Ansible Default User (ansadmin)
  ansible.builtin.user:
    name: ansadmin
    state: present
    shell: /bin/bash
    create_home: true
    password: "{{ansadmin_password_hash}}"
    update_password: on_create

- name: Ensuring SUDO is Installed
  ansible.builtin.package:
    name: sudo
    state: present

- name: Allowing ansadmin Passwordless Sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ansadmin
    content: "ansadmin ALL=(ALL) NOPASSWD: ALL"

#Setting-up NodeJS
- name: Disabling NodeJS Default Version (10)
  ansible.builtin.command: "dnf module disable nodejs -y"

- name: Enabling Required NodeJS Version (18)
  ansible.builtin.command: "dnf module enable nodejs:18 -y"

- name: Installing NodeJs Version 18
  ansible.builtin.package:
    name: nodejs
    state: present

#Setting-up Catalogue Microservice
- name: Downloading Catalogue Application Code
  ansible.builting.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/catalogue.zip"
    dest: "/tmp/catalogue.zip"

- name: Unzipping Catalogue Application Code into /app
  ansible.builtin.unarchive:
    src: "/tmp/catalogue.zip"
    dest: "/app"
    remote_src: true

- name: Installing Catalogue Application Dependencies
  ansible.builtin.command: "npm install"
  args:
    chdir: /app
    creates: /app/node_modules

- name: Copying catalogue.service.j2 as /etc/systemd/system/catalogue.service
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service
    mode: "0644"

- name: Reloading systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enabling and Starting Catalogue Service
  ansible.builtin.systemd:
    name: catalogue
    state: started
    enabled: true

#Loading Catalogue Schema into MongoDB Database
- name: Copying mongodb.repo as /etc/yum.repos.d/mongodb.repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing MongoDB Client
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: Loading Catalogue Schema into MongoDB Database
  ansible.builtin.shell: "mongo --host mongodb.optimusprime.sbs </app/schema/catalogue.js"
