---
# tasks file for cart

#Setting-up Roboshop Application Basic Requirements
- name: Run Roboshop Application Basic Requirements (from common to cart microservice)
  ansible.buitlin.import_role:
    name: common
    tasks_from: roboshop_basic_requirements.yml

#Setting-up NodeJS
- name: Installing NodeJS (from common to cart microservice)
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs_installation.yml

#Setting-up Cart Microservice
- name: Downloading and Unzipping Cart Microservice Application Code (from common to cart microservice)
  ansible.builtin.import_role:
    name: common
    tasks_from: download_unzip_service.yml

- name: Installing Cart Application Dependencies
  ansible.builtin.command: "npm install"
  args:
    chdir: /app

- name: Copying cart.service.j2 as /etc/systemd/system/cart.service
  ansible.builtin.template:
    src: cart.service.j2
    dest: /etc/systemd/system/cart.service
  notify: Reload systemd daemon

- name: Enabling and Staring Cart Service
  ansbile.builtin.systemd:
    name: cart
    state: started
    enabled: true


