---
# tasks file for cart
#Roboshop Application Basic Requirements have been called from /roles/common/main.yml

#Setting-up NodeJS
- name: Disabling NodeJS Default Version (10)
  ansible.builtin.command: "dnf module disable nodejs -y"

- name: Enabling NodeJS Required Version (18)
  ansible.builtin.command: "dnf module enable nodejs:18 -y"

- name: Installing NodeJS Required Version (18)
  ansible.builtin.package:
    name: nodejs
    state: present

#Setting-up Cart Microservice
- name: Downloading Cart Microservice Application Code
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/cart.zip
    dest: /tmp/cart.zip

- name: Unzipping Cart Microservice Application Code
  ansible.builtin.unarchive:
    src: /tmp/cart.zip
    dest: /app
    remote_src: true

- name: Installing Cart Application Dependencies
  ansible.builtin.command: "npm install"
  args:
    chdir: /app

- name: Copying cart.service.j2 as /etc/systemd/system/cart.service
  ansible.builtin.template:
    src: cart.service.j2
    dest: /etc/systemd/system/cart.service

- name: Reloading systemd daemon Service
  ansbile.builtin.systemd:
    daemon_reload: true

- name: Enabling and Staring Cart Service
  ansbile.builtin.systemd:
    name: cart
    state: started
    enabled: true


