roboshop_password_plain: RoboShop@1
ansadmin_password_plain: admin

redis_host: redis.optimusprime.sbs

catalogue_host: catalogue.optimusprime.sbs
catalogue_port: 8080

mongo_host: mongodb.optimusprime.sbs
mongo_port: 27017

rabbitmq_host: rabbitmq.optimusprime.sbs
