$ANSIBLE_VAULT;1.1;AES256
38323365383336333331366265353132336638356130626464323935613061336335396462316232
3235663239613133313232316166363763313037353834310a613134633163623266646263313362
30393436653536623834626339353930643831393765646234643466626563383266616438663437
6131376363633261650a633261306466656630383939323963383766646430643962643030306563
62313036353631643832613035643163626165373964643131613134666464383139313061373137
30353435333563346336643634623764363162653931646132346635316262636361353861636239
32306438373534306666613038663036386236336238333634373838303838356164303064323961
62653331623864633739373862646463653536343633626539333865346564393839313732353433
36653935626433643739316632346136613563313536323862396237343331643364383732386363
64346136336166646561626536346639646264336262376361616534366337653761343061353639
37336337306335616334623035383630643133326338613934363831663465626435376632646232
63393138643066376235393238323239646531663563373762383035313162393935393163633963
36653332666435386634353662666139306330396535333837396361353433626237373230653164
32313837333832306439323733306163373935636361366230313438303764663565663265313831
32323038303335303137323231346132356538356139303266383234346366326138396530386432
63376131666663636637623565303732646132316237376165306466306337333135666130656630
3432
