$ANSIBLE_VAULT;1.1;AES256
66626466393732366530376262636336363835316632336465363932346466323762663866306436
6335613435316430666465363630656331343231636164620a646331313864333335616536623236
65373761643031353864623637326338306332396633336562346265643438666463356361373136
3135353439393438350a376337373532396535636561363639366166346531643030626465343337
30663664373233393233653438643061656262373133666130326237326239613839313437666434
34653135313634613630383737653837613731626532383437346638326435316539393763636665
32363864363339313734393436656336323661626635636266623631643362626536373637383464
35656566336539316138633134386466613764333763656236313164393731356565343033386234
32363164323766616265393337643739663364663930323138663939653365333533653532343737
3865303464386631653164386336323733626166353334343865
