$ANSIBLE_VAULT;1.1;AES256
36623134396237336132313633373366343230623837376439373261626535386132653430633561
6531366239346661343130376539636362353833663863660a613537626130633461313361326235
61303130366138616235363966363937306134303165333166653764376332373662346237613163
6136373736313236390a663439313531623133313834353730383263633837633465613339396133
62363661656162306532396261396435646537643838353763656164636434613464323535386335
39623339656537646262613430396261646334313530336164303562386532656461636363623636
39383832346363626334343262323161613739306138616663623666623362346264613465623166
37373732653434376466646435386634323238346334333339653262633134653236386131396664
33626639613032346238653364363930663139303131343364353365653832376535643862393632
6138613239623132346363303839656239323834356138376566
