---
# tasks file for rabbitmq
#Setting-up Roboshop Basic App Requirements
- name: Run Roboshop Application Basic Requirements (from common to rabbitmq microservice)
  ansible.builtin.import_role:
    name: common
    tasks_from: roboshop_basic_requirements.yml

#Setting-up RabbitMQ Database
- name: Creating RabbitMQ Dependencies (ErLang Repo)
  ansible.builtin.shell: "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
  args:
    creates: /etc/yum.repos.d/rabbitmq_erlang.repo

- name: Creating RabbitMQ Dependencies (RabbitMQ Server Repo)
  ansible.builtin.shell: "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"
  args:
    creates: /etc/yum.repos.d/rabbitmq_rabbitmq-server.repo

- name: Installing RabbitMQ Database
  ansible.builtin.import_role:
    name: common
    tasks_from: package_installer.yml

- name: Enabling and Starting RabbitMQ Database
  ansible.builtin.import_role:
    name: common
    tasks_from: enable_start_service.yml

#Setting-up RabbitMQ User and Enabling Permissions
- name: Creating RabbitMQ Database User (roboshop) with Password
  # ansible.builtin.command: "rabbitmqctl add_user roboshop roboshop123"
  ansible.builtin.shell: "rabbitmqctl list_users | awk '{print$1}' | grep -qx roboshop || rabbitmqctl add_user roboshop roboshop123 "

- name: Enabling RabbitMQ Database User (roboshop) Permissions
  ansible.builtin.command: 'rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"'
